"""enable refrsh token

Revision ID: 0503b671aa3e
Revises: 61659ea1a349
Create Date: 2025-03-15 15:03:17.883803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0503b671aa3e'
down_revision = '61659ea1a349'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
