"""Remove unique constraint from username

Revision ID: 61659ea1a349
Revises: 0fd3fc1cec58
Create Date: 2025-03-15 13:06:21.558959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61659ea1a349'
down_revision = '0fd3fc1cec58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_full_name', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_full_name', 'users', ['full_name'], unique=False)
    # ### end Alembic commands ###
